### PR TITLE
Add line shuffling and space removing (beta)  #7, #9

### PR DESCRIPTION
**Pull request by Ethosa**

### CODE REVIEW

**Comment by Ethosa** [comment]
This works in my project (~3k lines)

**Comment by cherriesandmochi** [comment]
Looks good, but I unfortunately can't merge it like that, as it breaks line assignments in source maps. I might work on it soon to have it properly link to the source lines.

**Comment by Ethosa** [comment]
> Looks good, but I unfortunately can't merge it like that, as it breaks line assignments in source maps. I might work on it soon to have it properly link to the source lines.

Sure, take my source if you need

**Comment by cherriesandmochi** [comment]
Closed by 7faaac7.

**Pull request closed without merging**
